# Site settings
title: Coursera Yandex Intro to Machine Learning
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Coursera Yandex Intro to Machine Learning — find the missing course materials here
baseurl: "/coursera-yandex-intro-to-machine-learning" # the subpath of your site, e.g. /blog/
url: "http://koddo.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  koddo

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/
